"""add common fields

Revision ID: 6e5abcaa6242
Revises: 738064f35caa
Create Date: 2022-11-05 23:43:27.139079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e5abcaa6242'
down_revision = '738064f35caa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('time_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('time_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'time_updated')
    op.drop_column('users', 'time_created')
    # ### end Alembic commands ###
